# Stage 1: Import dependencies for the project¶


In [1]:
import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

C:\Users\Ad\Anaconda3\envs\newenvt\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.__version__

'2.1.0'

# Stage 2: Dataset preprocessing

2.1Loading the dataset

In [3]:
#Loading the Fashion Mnist dataset
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
y_train.shape

(60000,)

In [6]:
X_test.shape

(10000, 28, 28)

In [7]:
y_test.shape

(10000,)

In [8]:
X_train[:5]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
   

In [9]:
y_train[:5]

array([9, 0, 0, 3, 0], dtype=uint8)

2.2 Image normalization

In [10]:
X_train = X_train / 255.0

In [11]:
X_test = X_test / 255.0

2.3 Reshaping of the dataset

In [12]:
#Since each image is 28x28, we simply use reshape the full dataset to [-1 (all elements), height * width]
X_train = X_train.reshape(-1, 28*28)

In [13]:
X_train.shape

(60000, 784)

In [14]:
#Reshape the testing subset in the same way
X_test = X_test.reshape(-1, 28*28)

In [15]:
X_test.shape

(10000, 784)

In [16]:
X_train[:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Stage 3: Building an Artificial Neural network# New Section


3.1 Defining the model

In [17]:
model = tf.keras.models.Sequential()

3.2 Adding the layers (Dense layer) and dropout

In [18]:
'''model.add(tf.keras.layers.Dense(units=32, activation='relu', input_shape=(784, )))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units=64, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))  #intentionally high dropout is taken to check model behaviour
model.add(tf.keras.layers.Dense(units=128, activation='relu'))
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))'''

#above one accounts for low accuracy

model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784, )))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

3.3 Compiling the model

Optimizer: Adam  
Loss: Sparse softmax (categorical) crossentropy

In [20]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [22]:
#784*128+128=100480,  128 are 1 bias term each for 128 neurons
#128*10+10=1290,   10 are 1 bias term each for 10 neurons
100480+1290

101770


# Stage 4: Training the model

In [23]:
model.fit(X_train, y_train, epochs=15)

Train on 60000 samples
Epoch 1/15
60000/60000 [==============================] - 10s 170us/sample - loss: 0.5258 - sparse_categorical_accuracy: 0.8127
Epoch 2/15
60000/60000 [==============================] - 7s 118us/sample - loss: 0.3983 - sparse_categorical_accuracy: 0.8557
Epoch 3/15
60000/60000 [==============================] - 7s 119us/sample - loss: 0.3645 - sparse_categorical_accuracy: 0.8671
Epoch 4/15
60000/60000 [==============================] - 7s 125us/sample - loss: 0.3432 - sparse_categorical_accuracy: 0.8734
Epoch 5/15
60000/60000 [==============================] - 7s 119us/sample - loss: 0.3276 - sparse_categorical_accuracy: 0.8801
Epoch 6/15
60000/60000 [==============================] - 7s 120us/sample - loss: 0.3162 - sparse_categorical_accuracy: 0.8833
Epoch 7/15
60000/60000 [==============================] - 7s 122us/sample - loss: 0.3079 - sparse_categorical_accuracy: 0.8863
Epoch 8/15
60000/60000 [==============================] - 8s 126us/sample - loss: 0.296

# Stage 5: Model evaluation and prediction

In [24]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

10000/10000 [==============================] - 1s 104us/sample - loss: 0.3361 - sparse_categorical_accuracy: 0.8839


In [25]:
print("Test accuracy: {}".format(test_accuracy))

Test accuracy: 0.883899986743927
